version: '4'
services:
  db:
    image: postgres
    container_name: task-manager
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - task-manager:/var/lib/postgresql/data

volumes:
  task-manager:
    external: true
